<?php

namespace Database\Seeders;

use App\Models\Symptom;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class SymptomSeeder extends Seeder
{
    public function run(): void
    {
        // Define translations directly in the seeder
        $translations = [
            'Mild Fever' => 'হালকা জ্বর',
            'Low-grade Fever' => 'নিম্ন-গ্রেড জ্বর',
            'Intermittent Fever' => 'মাঝে মাঝে জ্বর',
            'Persistent Fever' => 'ক্রমাগত জ্বর',
            'Fever with Rash' => 'জ্বর সহ ফুসকুড়ি',
            'General Malaise' => 'সাধারণ অসুস্থতা',
            'Body Heaviness' => 'শরীর ভারীভাব',
            'Exhaustion' => 'ক্লান্তি',
            'Poor Stamina' => 'দুর্বল সহনশীলতা',
            'Post-exertional Fatigue' => 'পরিশ্রম পরবর্তী ক্লান্তি',
            'Lightheadedness' => 'মাথা হালকা লাগা',
            'Vertigo' => 'ভার্টিগো',
            'Spinning Sensation' => 'ঘুরানো অনুভূতি',
            'Near Fainting' => 'প্রায় অজ্ঞান হওয়া',
            'Blackout Episodes' => 'অজ্ঞান হওয়ার ঘটনা',
            'Photophobia' => 'আলোর প্রতি অসহিষ্ণুতা',
            'Phonophobia' => 'শব্দের প্রতি অসহিষ্ণুতা',
            'Scalp Tenderness' => 'মাথার ত্বকে ব্যথা',
            'Sinus Headache' => 'সাইনাস মাথাব্যথা',
            'Frontal Headache' => 'কপালে মাথাব্যথা',
            'Occipital Headache' => 'মাথার পেছনে ব্যথা',
            'Neck Stiffness' => 'ঘাড় শক্ত হওয়া',
            'Neck Spasm' => 'ঘাড়ে খিঁচুনি',
            'Facial Pain' => 'মুখে ব্যথা',
            'Facial Numbness' => 'মুখ অসাড় হওয়া',
            'Dry Eyes' => 'চোখ শুকানো',
            'Watery Eyes' => 'চোখ দিয়ে পানি পড়া',
            'Red Eyes' => 'চোখ লাল হওয়া',
            'Eye Redness' => 'চোখের লালভাব',
            'Eye Discharge' => 'চোখ দিয়ে স্রাব',
            'Eyelid Swelling' => 'চোখের পাতা ফোলা',
            'Itchy Eyes' => 'চোখ চুলকানো',
            'Eye Irritation' => 'চোখে জ্বালাপোড়া',
            'Visual Aura' => 'দৃষ্টি আভা',
            'Floaters' => 'চোখের সামনে উড়ন্ত বিন্দু',
            'Ear Fullness' => 'কানে ভরা ভরা লাগা',
            'Ear Discharge' => 'কান থেকে স্রাব',
            'Reduced Hearing' => 'শ্রবণশক্তি কমে যাওয়া',
            'Sore Ears' => 'কানে ব্যথা',
            'Blocked Ears' => 'কান বন্ধ লাগা',
            'Throat Irritation' => 'গলায় জ্বালাপোড়া',
            'Dry Throat' => 'গলা শুকানো',
            'Scratchy Throat' => 'গলায় খসখসে ভাব',
            'Tonsil Swelling' => 'টনসিল ফোলা',
            'Bad Breath' => 'নিঃশ্বাসে দুর্গন্ধ',
            'Loss of Smell' => 'গন্ধ পাওয়া কমে যাওয়া',
            'Reduced Smell' => 'গন্ধ অনুভূতি হ্রাস',
            'Loss of Taste' => 'স্বাদ অনুভূতি হ্রাস',
            'Reduced Taste' => 'স্বাদ কমে যাওয়া',
            'Postnasal Drip' => 'নাক দিয়ে পানি গলায় পড়া',
            'Nasal Itching' => 'নাক চুলকানো',
            'Facial Congestion' => 'মুখমণ্ডলে চাপ',
            'Chest Congestion' => 'বুকে চাপ',
            'Productive Cough' => 'কফসহ কাশি',
            'Dry Cough' => 'শুকনো কাশি',
            'Nocturnal Cough' => 'রাতের কাশি',
            'Cough with Blood' => 'রক্তসহ কাশি',
            'Breathlessness on Exertion' => 'পরিশ্রমে শ্বাসকষ্ট',
            'Breathlessness at Rest' => 'বিশ্রামে শ্বাসকষ্ট',
            'Painful Breathing' => 'কষ্ট করে শ্বাস নেওয়া',
            'Rapid Pulse' => 'দ্রুত নাড়ি',
            'Irregular Heartbeat' => 'অনিয়মিত হৃদস্পন্দন',
            'Skipped Heartbeats' => 'হৃদস্পন্দন ছেড়ে যাওয়া',
            'Orthopnea' => 'শুয়ে শ্বাসকষ্ট',
            'Pitting Edema' => 'চাপ দিলে দাগ পড়া ফোলা',
            'Hand Swelling' => 'হাত ফোলা',
            'Ankle Swelling' => 'গোড়ালি ফোলা',
            'Foot Numbness' => 'পা অসাড় হওয়া',
            'Burning Feet' => 'পায়ে জ্বালাপোড়া',
            'Cold Sweats' => 'ঠান্ডা ঘাম',
            'Abdominal Cramps' => 'পেটে ব্যথা',
            'Upper Abdominal Pain' => 'উপরের পেটে ব্যথা',
            'Lower Abdominal Pain' => 'নিচের পেটে ব্যথা',
            'Right Upper Quadrant Pain' => 'ডান পাঁজরের নিচে ব্যথা',
            'Left Upper Quadrant Pain' => 'বাম পাঁজরের নিচে ব্যথা',
            'Epigastric Pain' => 'পেটের মাঝখানে ব্যথা',
            'Indigestion' => 'বদহজম',
            'Early Satiety' => 'অল্প খাবারেই পেট ভরা',
            'Poor Digestion' => 'হজমের সমস্যা',
            'Sour Belching' => 'টক ঢেকুর',
            'Acid Reflux' => 'এসিড রিফ্লাক্স',
            'Burning Stomach' => 'পেট জ্বালাপোড়া',
            'Mucus in Stool' => 'পায়খানায় শ্লেষ্মা',
            'Loose Stools' => 'ঢিলা পায়খানা',
            'Hard Stools' => 'শক্ত পায়খানা',
            'Urgency to Defecate' => 'হঠাৎ পায়খানার তাগিদ',
            'Tenesmus' => 'পায়খানার পরও তাগিদ থাকা',
            'Painful Defecation' => 'পায়খানায় ব্যথা',
            'Rectal Bleeding' => 'পায়খানার পথে রক্ত',
            'Dark Stools' => 'কালো পায়খানা',
            'Pale Stools' => 'ফ্যাকাশে পায়খানা',
            'Frequent Bowel Movements' => 'বারবার পায়খানা',
            'Infrequent Bowel Movements' => 'কম পায়খানা',
            'Bitter Taste' => 'মুখে তেতো স্বাদ',
            'Dry Lips' => 'ঠোঁট শুকানো',
            'Frequent Night Urination' => 'রাতে বারবার প্রস্রাব',
            'Urinary Urgency' => 'হঠাৎ প্রস্রাবের তাগিদ',
            'Urinary Hesitancy' => 'প্রস্রাব শুরু করতে কষ্ট',
            'Weak Urine Stream' => 'দুর্বল প্রস্রাবের ধারা',
            'Incomplete Bladder Emptying' => 'মূত্রাশয় পুরোপুরি খালি না হওয়া',
            'Urinary Incontinence' => 'প্রস্রাব ধরে রাখতে না পারা',
            'Foul-smelling Urine' => 'প্রস্রাবে দুর্গন্ধ',
            'Cloudy Urine' => 'প্রস্রাব ঘোলা হওয়া',
            'Flank Pain' => 'কোমরে ব্যথা',
            'Lower Back Ache' => 'কোমরের নিচে ব্যথা',
            'Pelvic Pressure' => 'পেলভিসে চাপ',
            'Lower Pelvic Cramps' => 'পেলভিসের নিচে ব্যথা',
            'Menstrual Cramps' => 'মাসিকের ব্যথা',
            'Heavy Menstrual Bleeding' => 'অত্যাধিক মাসিক রক্তপাত',
            'Irregular Menstruation' => 'অনিয়মিত মাসিক',
            'Missed Periods' => 'মাসিক বন্ধ থাকা',
            'Painful Intercourse' => 'মিলনে ব্যথা',
            'Vaginal Discharge' => 'যোনি স্রাব',
            'Vaginal Itching' => 'যোনি চুলকানি',
            'Breast Tenderness' => 'স্তনে ব্যথা',
            'Nipple Discharge' => 'স্তনের বোঁটা থেকে স্রাব',
            'Erectile Dysfunction' => 'ইরেক্টাইল ডিসফাংশন',
            'Reduced Libido' => 'যৌন ইচ্ছা কমে যাওয়া',
            'Testicular Pain' => 'টেস্টিসে ব্যথা',
            'Scrotal Swelling' => 'স্ক্রোটাম ফোলা',
            'Muscle Weakness' => 'পেশি দুর্বলতা',
            'Muscle Stiffness' => 'পেশি শক্ত হওয়া',
            'Muscle Twitching' => 'পেশি কুঁচকানো',
            'Calf Pain' => 'বাছায় ব্যথা',
            'Thigh Pain' => 'উরুতে ব্যথা',
            'Shin Pain' => 'হাড়ের সম্মুখভাগে ব্যথা',
            'Heel Pain' => 'গোড়ালিতে ব্যথা',
            'Foot Pain' => 'পায়ে ব্যথা',
            'Toe Pain' => 'পায়ের আঙুলে ব্যথা',
            'Finger Joint Pain' => 'আঙুলের জয়েন্টে ব্যথা',
            'Hand Joint Stiffness' => 'হাতের জয়েন্ট শক্ত হওয়া',
            'Morning Stiffness' => 'সকালে শক্ত হয়ে যাওয়া',
            'Limited Range of Motion' => 'নড়াচড়ার সীমিত পরিধি',
            'Back Spasm' => 'পিঠে খিঁচুনি',
            'Lower Back Stiffness' => 'কোমরের নিচে শক্ত হওয়া',
            'Upper Back Pain' => 'পিঠের উপরের দিকে ব্যথা',
            'Shoulder Stiffness' => 'কাঁধ শক্ত হওয়া',
            'Arm Numbness' => 'বাহু অসাড় হওয়া',
            'Hand Numbness' => 'হাত অসাড় হওয়া',
            'Leg Numbness' => 'পা অসাড় হওয়া',
            'Pins and Needles' => 'শিরশিরানি',
            'Burning Sensation' => 'জ্বালাপোড়া অনুভূতি',
            'Electric Shock Sensation' => 'বৈদ্যুতিক শকের মতো অনুভূতি',
            'Restless Legs' => 'অস্থির পা',
            'Unsteady Gait' => 'হাঁটতে অসুবিধা',
            'Sleep Disturbance' => 'ঘুমের সমস্যা',
            'Daytime Sleepiness' => 'দিনের বেলা ঘুম পাওয়া',
            'Frequent Awakening' => 'বারবার ঘুম ভাঙা',
            'Snoring' => 'নাক ডাকা',
            'Breathing Pauses During Sleep' => 'ঘুমের সময় শ্বাস বন্ধ হওয়া',
            'Poor Sleep Quality' => 'খারাপ মানের ঘুম',
            'Vivid Dreams' => 'তীব্র স্বপ্ন দেখা',
            'Nightmares' => 'দুঃস্বপ্ন দেখা',
            'Teeth Grinding' => 'দাঁত কিড়মিড় করা',
            'Jaw Clenching' => 'চোয়াল চেপে ধরা',
            'Dry Cough at Night' => 'রাতে শুকনো কাশি',
            'Exercise Intolerance' => 'ব্যায়াম সহ্য করতে না পারা',
            'Dehydration' => 'পানি শূন্যতা',
            'Sun Sensitivity' => 'রোদে সংবেদনশীলতা',
            'Heat Intolerance' => 'গরম সহ্য করতে না পারা',
            'Cold Intolerance' => 'ঠান্ডা সহ্য করতে না পারা',
            'Hand Tremor' => 'হাত কাঁপুনি',
            'Shakiness' => 'কাঁপুনি',
            'Speech Difficulty' => 'কথা বলতে অসুবিধা',
            'Word Finding Difficulty' => 'শব্দ খুঁজে পেতে অসুবিধা',
            'Slow Speech' => 'ধীর গতির কথা',
            'Slurred Speech' => 'অস্পষ্ট কথা',
            'Confused Speech' => 'বিভ্রান্তিকর কথা',
            'Reduced Alertness' => 'সতর্কতা হ্রাস',
            'Difficulty Concentrating' => 'মনোযোগ দিতে অসুবিধা',
            'Irritable Mood' => 'খিটখিটে মেজাজ',
            'Low Mood' => 'মেজাজ খারাপ থাকা',
            'Hopelessness' => 'হতাশা',
            'Feeling Nervous' => 'নার্ভাস অনুভব করা',
            'Excessive Worry' => 'অতিরিক্ত উদ্বেগ',
            'Panic Feeling' => 'আতঙ্ক অনুভব',
            'Social Withdrawal' => 'সামাজিক বিচ্ছিন্নতা',
            'Loss of Interest' => 'আগ্রহ হারানো',
            'Emotional Numbness' => 'আবেগহীনতা',
            'Crying Spells' => 'কান্নার প্রবণতা',
            'Skin Dryness' => 'ত্বক শুকানো',
            'Skin Peeling' => 'ত্বক খসখসে হওয়া',
            'Skin Redness' => 'ত্বক লাল হওয়া',
            'Skin Warmth' => 'ত্বক গরম থাকা',
            'Skin Tightness' => 'ত্বক টানটান লাগা',
            'Hives' => 'চুলকানি ফোলা',
            'Blisters' => 'ফোসকা',
            'Pustules' => 'পুঁজ ভর্তি ফোস্কা',
            'Acne Breakouts' => 'ব্রণ হওয়া',
            'Facial Flushing' => 'মুখ লাল হয়ে যাওয়া',
            'Dark Patches on Skin' => 'ত্বকে কালো দাগ',
            'Pale Lips' => 'ঠোঁট ফ্যাকাশে হওয়া',
            'Brittle Nails' => 'নখ ভঙ্গুর হওয়া',
            'Nail Discoloration' => 'নখের রং পরিবর্তন',
            'Hair Thinning' => 'চুল পাতলা হওয়া',
            'Scalp Itching' => 'মাথার ত্বক চুলকানো',
            'Scalp Flaking' => 'মাথার ত্বকে খুশকি',
            'Delayed Wound Healing' => 'ক্ষত শুকাতে দেরি হওয়া',
            'Easy Bleeding' => 'সহজে রক্তপাত হওয়া',
            'Frequent Infections' => 'বারবার সংক্রমণ',
            'Frequent Bruising' => 'সহজে কালশিরে পড়া',
            'Swollen Glands' => 'গ্রন্থি ফোলা',
            'Mouth Dryness' => 'মুখ শুকানো',
            'Tongue Pain' => 'জিহ্বায় ব্যথা',
            'Tongue Ulcer' => 'জিহ্বায় ঘা',
            'Mouth Burning' => 'মুখ জ্বালাপোড়া',
            'Loss of Voice' => 'কণ্ঠস্বর চলে যাওয়া',
            'Voice Fatigue' => 'কণ্ঠস্বর দুর্বল হওয়া',
            'Persistent Hoarseness' => 'ক্রমাগাত গলা বসে যাওয়া',
            'Difficulty Speaking' => 'কথা বলতে অসুবিধা',
            'Shallow Breathing' => 'অগভীর শ্বাস',
            'Chest Heaviness' => 'বুকে চাপ',
            'Pleural Pain' => 'ফুসফুসের আস্তরণে ব্যথা',
            'Pain on Coughing' => 'কাশিতে ব্যথা',
            'Exercise-induced Wheezing' => 'ব্যায়ামে হাঁপানি',
            'Post-meal Sleepiness' => 'খাবারের পরে ঘুম পাওয়া',
            'Post-meal Bloating' => 'খাবারের পরে পেট ফাঁপা',
            'Food Intolerance' => 'খাবারে অসহিষ্ণুতা',
            'Milk Intolerance' => 'দুধে অসহিষ্ণুতা',
            'Gluten Intolerance' => 'গ্লুটেনে অসহিষ্ণুতা',
            'Motion Sickness' => 'যানবাহনে বমি বমি ভাব',
            'Travel Sickness' => 'ভ্রমণে অসুস্থতা',
            'Nausea After Meals' => 'খাবারের পরে বমি বমি ভাব',
            'Morning Nausea' => 'সকালে বমি বমি ভাব',
            'Dry Heaving' => 'শুকনো বমি',
            'Vomiting After Meals' => 'খাবারের পরে বমি',
            'Persistent Vomiting' => 'ক্রমাগাত বমি',
            'Excessive Hunger' => 'অতিরিক্ত ক্ষুধা',
            'Increased Appetite' => 'খিদে বেড়ে যাওয়া',
            'Reduced Urine Output' => 'প্রস্রাব কম হওয়া',
            'Excessive Urine Output' => 'অতিরিক্ত প্রস্রাব',
            'Puffiness Around Eyes' => 'চোখের চারপাশে ফোলা',
            'Facial Swelling' => 'মুখমণ্ডল ফোলা',
            'Neck Swelling' => 'ঘাড় ফোলা',
            'Throat Swelling' => 'গলা ফোলা',
            'Difficulty Opening Mouth' => 'মুখ খুলতে অসুবিধা',
            'Painful Swallowing' => 'গিলতে ব্যথা',
            'Choking Sensation' => 'শ্বাসরোধের মতো অনুভব',
            'Lump in Throat' => 'গলায় পিণ্ডের মতো অনুভব',
            'Burning Chest' => 'বুকে জ্বালাপোড়া',
            'Heart Fluttering' => 'বুক দুরু দুরু করা',
            'Chest Pressure' => 'বুকে চাপ',
            'Radiating Chest Pain' => 'বুকে ব্যথা ছড়িয়ে পড়া',
            'Left Arm Pain' => 'বাম বাহুতে ব্যথা',
            'Jaw Tightness' => 'চোয়াল শক্ত হয়ে যাওয়া',
            'Right Shoulder Pain' => 'ডান কাঁধে ব্যথা',
            'Generalized Itching' => 'সারা শরীর চুলকানি',
            'Anal Itching' => 'পায়ুপথ চুলকানি',
            'Rash on Face' => 'মুখে ফুসকুড়ি',
            'Rash on Trunk' => 'বুকে-পেটে ফুসকুড়ি',
            'Rash on Limbs' => 'হাত-পায়ে ফুসকুড়ি',
            'Patchy Hair Loss' => 'চুল দাগে দাগে পড়া',
            'Dry Cough with Fever' => 'জ্বরসহ শুকনো কাশি',
            'Persistent Sneezing' => 'ক্রমাগাত হাঁচি',
            'Chronic Runny Nose' => 'দীর্ঘমেয়াদী নাক দিয়ে পানি পড়া',
        ];

        $allSymptoms = collect(array_keys($translations))
            ->merge($extraSymptoms ?? [])
            ->map(fn($name) => trim((string) $name))
            ->filter()
            ->unique()
            ->values();

        foreach ($allSymptoms as $symptomName) {
            // Get translation from the array
            $bangla = $translations[$symptomName] ?? $symptomName;

            $payload = [];
            if (Schema::hasColumn('symptoms', 'bangla_name')) {
                $payload['bangla_name'] = $bangla;
            }
            if (Schema::hasColumn('symptoms', 'name_bn')) {
                $payload['name_bn'] = $bangla;
            }

            Symptom::updateOrCreate(
                ['name' => $symptomName],
                $payload
            );
        }

        $this->command?->info('Symptoms seeded: ' . $allSymptoms->count());
    }
}