<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Symptoms List with Bangla Translations (102+)
    |--------------------------------------------------------------------------
    */
    'symptoms' => [
        // General / Constitutional
        'Fever' => 'জ্বর',
        'High Fever' => 'তীব্র জ্বর',
        'Chills' => 'শীত শীত ভাব',
        'Fatigue' => 'ক্লান্তি',
        'Weakness' => 'দুর্বলতা',
        'Drowsiness' => 'তন্দ্রাভাব',
        'Lethargy' => 'অলসতা',
        'Night Sweats' => 'রাতে ঘাম',
        'Excessive Sweating' => 'অতিরিক্ত ঘাম',
        'Weight Loss' => 'ওজন কমা',
        'Weight Gain' => 'ওজন বৃদ্ধি',
        'Loss of Appetite' => 'ক্ষুধামন্দা',

        // Head & Neuro
        'Headache' => 'মাথাব্যথা',
        'Dizziness' => 'মাথা ঘোরা',
        'Fainting' => 'অজ্ঞান হওয়া',
        'Seizure' => 'খিঁচুনি',
        'Tremor' => 'কাঁপুনি',
        'Confusion' => 'বিভ্রান্তি',
        'Memory Loss' => 'স্মৃতিশক্তি কমা',
        'Poor Concentration' => 'মনোযোগহীনতা',
        'Forgetfulness' => 'ভুলে যাওয়া',
        'Balance Problems' => 'ভারসাম্যহীনতা',
        'Stiff Neck' => 'ঘাড় শক্ত হওয়া',

        // Eyes
        'Blurred Vision' => 'ঝাপসা দৃষ্টি',
        'Double Vision' => 'দ্বিতীয় দৃষ্টি',
        'Vision Loss' => 'দৃষ্টিশক্তি হ্রাস',
        'Eye Pain' => 'চোখে ব্যথা',
        'Burning Eyes' => 'চোখ জ্বালা',

        // Ears, Nose, Throat
        'Ear Pain' => 'কানে ব্যথা',
        'Tinnitus' => 'কানে শব্দ',
        'Sore Throat' => 'গলা ব্যথা',
        'Hoarseness' => 'গলা ভাঙা',
        'Difficulty Swallowing' => 'গিলতে সমস্যা',
        'Runny Nose' => 'নাক দিয়ে পানি পড়া',
        'Nasal Congestion' => 'নাক বন্ধ থাকা',
        'Nosebleed' => 'নাক দিয়ে রক্ত পড়া',
        'Sneezing' => 'হাঁচি',
        'Toothache' => 'দাঁতে ব্যথা',
        'Mouth Ulcer' => 'মুখের ঘা',
        'Bleeding Gums' => 'মাড়ি থেকে রক্তপাত',
        'Jaw Pain' => 'চোয়ালে ব্যথা',

        // Respiratory
        'Cough' => 'কাশি',
        'Cold' => 'সর্দি',
        'Shortness of Breath' => 'শ্বাসকষ্ট',
        'Wheezing' => 'শ্বাসে শব্দ',
        'Rapid Breathing' => 'দ্রুত শ্বাস',
        'Chest Tightness' => 'বুক আঁটসাঁট',

        // Cardiovascular
        'Chest Pain' => 'বুকে ব্যথা',
        'Palpitations' => 'বুক ধড়ফড়',
        'Rapid Heart Rate' => 'দ্রুত হৃদস্পন্দন',
        'Swollen Feet' => 'পা ফোলা',
        'Water Retention' => 'জল ধারণ',
        'Pale Skin' => 'ফ্যাকাশে ত্বক',
        'Yellow Skin' => 'জন্ডিস',
        'Cold Extremities' => 'হাত-পা ঠান্ডা হওয়া',

        // Digestive
        'Nausea' => 'বমি বমি ভাব',
        'Vomiting' => 'বমি',
        'Vomiting Blood' => 'রক্ত বমি',
        'Diarrhea' => 'ডায়রিয়া',
        'Constipation' => 'কোষ্ঠকাঠিন্য',
        'Bloating' => 'পেট ফাঁপা',
        'Swollen Abdomen' => 'পেট ফোলা',
        'Heartburn' => 'বুক জ্বালা',
        'Abdominal Pain' => 'পেটে ব্যথা',
        'Gas Pain' => 'গ্যাসের ব্যথা',
        'Hiccups' => 'হেঁচকি',
        'Belching' => 'ঢেকুর',
        'Blood in Stool' => 'পায়খানায় রক্ত',

        // Urinary
        'Frequent Urination' => 'ঘন ঘন প্রস্রাব',
        'Urinary Burning' => 'প্রস্রাবে জ্বালা',
        'Blood in Urine' => 'প্রস্রাবে রক্ত',
        'Dark Urine' => 'গাঢ় প্রস্রাব',
        'Dry Mouth' => 'শুষ্ক মুখ',
        'Excessive Thirst' => 'অতিরিক্ত তৃষ্ণা',

        // Musculoskeletal
        'Body Pain' => 'শরীর ব্যথা',
        'Joint Pain' => 'জয়েন্টে ব্যথা',
        'Muscle Pain' => 'পেশী ব্যথা',
        'Back Pain' => 'পিঠে ব্যথা',
        'Neck Pain' => 'ঘাড়ে ব্যথা',
        'Shoulder Pain' => 'কাঁধে ব্যথা',
        'Knee Pain' => 'হাঁটুতে ব্যথা',
        'Hip Pain' => 'কোমরে ব্যথা',
        'Wrist Pain' => 'কব্জিতে ব্যথা',
        'Ankle Pain' => 'গোড়ালিতে ব্যথা',
        'Elbow Pain' => 'কনুইতে ব্যথা',
        'Leg Cramps' => 'পায়ে খিল ধরা',
        'Stiffness' => 'জড়তা',
        'Pelvic Pain' => 'পেলভিক ব্যথা',
        'Groin Pain' => 'কুঁচকিতে ব্যথা',
        'Rib Pain' => 'পাঁজরে ব্যথা',

        // Neurological / Sensory
        'Numbness' => 'অবশ ভাব',
        'Tingling' => 'ঝিনঝিন করা',
        'Swollen Lymph Nodes' => 'লিম্ফ নোড ফোলা',

        // Skin
        'Skin Rash' => 'চামড়ায় ফুসকুড়ি',
        'Itching' => 'চুলকানি',
        'Swelling' => 'ফোলা',
        'Bruising' => 'ক্ষত চিহ্ন',
        'Dry Skin' => 'শুষ্ক ত্বক',
        'Hair Loss' => 'চুল পড়া',

        // Mental / Emotional
        'Anxiety' => 'উদ্বেগ',
        'Depression' => 'বিষণ্নতা',
        'Insomnia' => 'অনিদ্রা',
        'Irritability' => 'খিটখিটে মেজাজ',
        'Mood Swings' => 'মেজাজের পরিবর্তন',
        'Panic Attacks' => 'প্যানিক অ্যাটাক',
        'Restlessness' => 'অস্থিরতা',
    ],

    /*
    |--------------------------------------------------------------------------
    | Health Metric Types with Bangla + Field Definitions (15 types)
    |--------------------------------------------------------------------------
    */
    'metric_types' => [
        'blood_pressure' => [
            'en' => 'Blood Pressure',
            'bn' => 'রক্তচাপ',
            'unit' => 'mmHg',
            'fields' => ['systolic', 'diastolic'],
            'js_fields' => [
                ['name' => 'value_systolic', 'label' => 'Systolic', 'placeholder' => 'e.g., 120', 'min' => 60, 'max' => 250],
                ['name' => 'value_diastolic', 'label' => 'Diastolic', 'placeholder' => 'e.g., 80', 'min' => 40, 'max' => 160],
            ],
        ],
        'blood_glucose' => [
            'en' => 'Blood Glucose',
            'bn' => 'রক্তের গ্লুকোজ',
            'unit' => 'mg/dL',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Glucose Level (mg/dL)', 'placeholder' => 'e.g., 110', 'min' => 30, 'max' => 600],
            ],
        ],
        'heart_rate' => [
            'en' => 'Heart Rate',
            'bn' => 'হৃদস্পন্দন',
            'unit' => 'bpm',
            'fields' => ['bpm'],
            'js_fields' => [
                ['name' => 'value_bpm', 'label' => 'Heart Rate (bpm)', 'placeholder' => 'e.g., 72', 'min' => 30, 'max' => 220],
            ],
        ],
        'body_weight' => [
            'en' => 'Body Weight',
            'bn' => 'শরীরের ওজন',
            'unit' => 'kg',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Weight (kg)', 'placeholder' => 'e.g., 68.5', 'min' => 1, 'max' => 300, 'step' => '0.1'],
            ],
        ],
        'bmi' => [
            'en' => 'BMI',
            'bn' => 'বিএমআই',
            'unit' => 'kg/m²',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'BMI (kg/m²)', 'placeholder' => 'e.g., 24.5', 'min' => 10, 'max' => 60, 'step' => '0.1'],
            ],
        ],
        'oxygen_saturation' => [
            'en' => 'Oxygen Saturation',
            'bn' => 'অক্সিজেন স্যাচুরেশন',
            'unit' => '%',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'SpO2 (%)', 'placeholder' => 'e.g., 98', 'min' => 50, 'max' => 100],
            ],
        ],
        'temperature' => [
            'en' => 'Temperature',
            'bn' => 'তাপমাত্রা',
            'unit' => '°C',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Temperature (°C)', 'placeholder' => 'e.g., 37.0', 'min' => 34, 'max' => 43, 'step' => '0.1'],
            ],
        ],
        'cholesterol' => [
            'en' => 'Cholesterol',
            'bn' => 'কোলেস্টেরল',
            'unit' => 'mg/dL',
            'fields' => ['total', 'hdl', 'ldl'],
            'js_fields' => [
                ['name' => 'value_total', 'label' => 'Total (mg/dL)', 'placeholder' => 'e.g., 200', 'min' => 50, 'max' => 500],
                ['name' => 'value_hdl', 'label' => 'HDL (mg/dL)', 'placeholder' => 'e.g., 60', 'min' => 10, 'max' => 200],
                ['name' => 'value_ldl', 'label' => 'LDL (mg/dL)', 'placeholder' => 'e.g., 100', 'min' => 10, 'max' => 400],
            ],
        ],
        'hemoglobin' => [
            'en' => 'Hemoglobin',
            'bn' => 'হিমোগ্লোবিন',
            'unit' => 'g/dL',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Hemoglobin (g/dL)', 'placeholder' => 'e.g., 14.0', 'min' => 3, 'max' => 25, 'step' => '0.1'],
            ],
        ],
        'creatinine' => [
            'en' => 'Creatinine',
            'bn' => 'ক্রিয়েটিনিন',
            'unit' => 'mg/dL',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Creatinine (mg/dL)', 'placeholder' => 'e.g., 1.0', 'min' => 0.1, 'max' => 20, 'step' => '0.1'],
            ],
        ],
        'respiratory_rate' => [
            'en' => 'Respiratory Rate',
            'bn' => 'শ্বাসের হার',
            'unit' => 'breaths/min',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Breaths/min', 'placeholder' => 'e.g., 16', 'min' => 5, 'max' => 60],
            ],
        ],
        'blood_urea' => [
            'en' => 'Blood Urea',
            'bn' => 'রক্তের ইউরিয়া',
            'unit' => 'mg/dL',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'BUN (mg/dL)', 'placeholder' => 'e.g., 15', 'min' => 1, 'max' => 200],
            ],
        ],
        'uric_acid' => [
            'en' => 'Uric Acid',
            'bn' => 'ইউরিক এসিড',
            'unit' => 'mg/dL',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Uric Acid (mg/dL)', 'placeholder' => 'e.g., 5.5', 'min' => 1, 'max' => 20, 'step' => '0.1'],
            ],
        ],
        'waist_circumference' => [
            'en' => 'Waist Circumference',
            'bn' => 'কোমরের পরিধি',
            'unit' => 'cm',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Circumference (cm)', 'placeholder' => 'e.g., 85', 'min' => 30, 'max' => 200, 'step' => '0.1'],
            ],
        ],
        'body_fat' => [
            'en' => 'Body Fat',
            'bn' => 'শরীরের চর্বি',
            'unit' => '%',
            'fields' => ['value'],
            'js_fields' => [
                ['name' => 'value_value', 'label' => 'Body Fat (%)', 'placeholder' => 'e.g., 22.5', 'min' => 1, 'max' => 60, 'step' => '0.1'],
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Disease Bangla Translations (120 diseases)
    |--------------------------------------------------------------------------
    */
    'diseases' => [
        'Diabetes Type 1' => 'ডায়াবেটিস টাইপ ১',
        'Diabetes Type 2' => 'ডায়াবেটিস টাইপ ২',
        'Hypertension' => 'উচ্চ রক্তচাপ',
        'Asthma' => 'হাঁপানি',
        'Chronic Kidney Disease' => 'দীর্ঘস্থায়ী কিডনি রোগ',
        'Heart Failure' => 'হার্ট ফেইলিওর',
        'Coronary Artery Disease' => 'করোনারি ধমনী রোগ',
        'COPD' => 'সিওপিডি',
        'Stroke' => 'স্ট্রোক',
        'Arthritis' => 'বাত',
        'Osteoporosis' => 'অস্টিওপোরোসিস',
        'Thyroid Disorder' => 'থাইরয়েড সমস্যা',
        'Anemia' => 'রক্তস্বল্পতা',
        'Depression' => 'বিষণ্নতা',
        'Anxiety Disorder' => 'উদ্বেগ রোগ',
        'Migraine' => 'মাইগ্রেন',
        'Epilepsy' => 'মৃগীরোগ',
        "Parkinson's Disease" => 'পারকিনসন রোগ',
        "Alzheimer's Disease" => 'আলঝেইমার রোগ',
        'Gastric Ulcer' => 'গ্যাস্ট্রিক আলসার',
        'GERD' => 'গার্ড',
        'Irritable Bowel Syndrome' => 'আইবিএস',
        'Liver Cirrhosis' => 'লিভার সিরোসিস',
        'Hepatitis B' => 'হেপাটাইটিস বি',
        'Hepatitis C' => 'হেপাটাইটিস সি',
        'Tuberculosis' => 'যক্ষ্মা',
        'Dengue Fever' => 'ডেঙ্গু জ্বর',
        'Malaria' => 'ম্যালেরিয়া',
        'Typhoid' => 'টাইফয়েড',
        'Measles' => 'হাম',
        'Chickenpox' => 'জলবসন্ত',
        'Psoriasis' => 'সোরিয়াসিস',
        'Eczema' => 'একজিমা',
        'Urinary Tract Infection' => 'মূত্রনালীর সংক্রমণ',
        'Kidney Stones' => 'কিডনি পাথর',
        'Gout' => 'গেঁটে বাত',
        'Rheumatoid Arthritis' => 'রিউমাটয়েড আর্থ্রাইটিস',
        'Lupus' => 'লুপাস',
        'Multiple Sclerosis' => 'মাল্টিপল স্ক্লেরোসিস',
        'Celiac Disease' => 'সেলিয়াক রোগ',
        'Fibromyalgia' => 'ফাইব্রোমায়ালজিয়া',
        'Chronic Fatigue Syndrome' => 'দীর্ঘস্থায়ী ক্লান্তি সিনড্রোম',
        'Sleep Apnea' => 'স্লিপ অ্যাপনিয়া',
        'Obesity' => 'স্থূলতা',
        'Vitamin D Deficiency' => 'ভিটামিন ডি ঘাটতি',
        'Iron Deficiency' => 'আয়রনের ঘাটতি',
        'High Cholesterol' => 'উচ্চ কোলেস্টেরল',
        'Fatty Liver' => 'ফ্যাটি লিভার',
        'Polycystic Ovary Syndrome' => 'পিসিওএস',
        'Endometriosis' => 'এন্ডোমেট্রিওসিস',
        'Prostate Enlargement' => 'প্রোস্টেট বড় হওয়া',
        'Pneumonia' => 'নিউমোনিয়া',
        'Bronchitis' => 'ব্রংকাইটিস',
        'Sinusitis' => 'সাইনোসাইটিস',
        'Tonsillitis' => 'টন্সিলাইটিস',
        'Appendicitis' => 'অ্যাপেন্ডিসাইটিস',
        'Gallstones' => 'পিত্তপাথর',
        'Pancreatitis' => 'প্যানক্রিয়াটাইটিস',
        'Peptic Ulcer Disease' => 'পেপটিক আলসার',
        "Crohn's Disease" => 'ক্রোন রোগ',
        'Ulcerative Colitis' => 'আলসারেটিভ কোলাইটিস',
        'Chronic Bronchitis' => 'দীর্ঘস্থায়ী ব্রংকাইটিস',
        'Emphysema' => 'এমফিসেমা',
        'Pulmonary Fibrosis' => 'পালমোনারি ফাইব্রোসিস',
        'Sarcoidosis' => 'সারকোইডোসিস',
        'Meningitis' => 'মেনিনজাইটিস',
        'Encephalitis' => 'এনসেফালাইটিস',
        "Bell's Palsy" => 'বেলস পলসি',
        'Carpal Tunnel Syndrome' => 'কার্পাল টানেল সিনড্রোম',
        'Sciatica' => 'সায়াটিকা',
        'Herniated Disc' => 'হার্নিয়েটেড ডিস্ক',
        'Osteoarthritis' => 'অস্টিওআর্থ্রাইটিস',
        'Bursitis' => 'বার্সাইটিস',
        'Tendinitis' => 'টেন্ডিনাইটিস',
        'Plantar Fasciitis' => 'প্লান্টার ফ্যাসাইটিস',
        'Scoliosis' => 'স্কোলিওসিস',
        'Cataracts' => 'ছানি',
        'Glaucoma' => 'গ্লুকোমা',
        'Macular Degeneration' => 'ম্যাকুলার ডিজেনারেশন',
        'Conjunctivitis' => 'কনজাংটিভাইটিস',
        'Retinopathy' => 'রেটিনোপ্যাথি',
        'Hearing Loss' => 'শ্রবণশক্তি হ্রাস',
        'Tinnitus' => 'টিনিটাস',
        'Vertigo' => 'ভার্টিগো',
        'Otitis Media' => 'কানের মধ্যে সংক্রমণ',
        'Deviated Septum' => 'নাকের হাড় বাঁকা',
        'Atrial Fibrillation' => 'অ্যাট্রিয়াল ফিব্রিলেশন',
        'Deep Vein Thrombosis' => 'ডিপ ভেইন থ্রম্বোসিস',
        'Pulmonary Embolism' => 'পালমোনারি এম্বোলিজম',
        'Peripheral Artery Disease' => 'পেরিফেরাল ধমনী রোগ',
        'Varicose Veins' => 'ভেরিকোজ ভেইন',
        'Leukemia' => 'লিউকেমিয়া',
        'Lymphoma' => 'লিম্ফোমা',
        'Breast Cancer' => 'স্তন ক্যান্সার',
        'Lung Cancer' => 'ফুসফুসের ক্যান্সার',
        'Colorectal Cancer' => 'কোলোরেক্টাল ক্যান্সার',
        'Prostate Cancer' => 'প্রোস্টেট ক্যান্সার',
        'Skin Cancer' => 'ত্বকের ক্যান্সার',
        'Thyroid Cancer' => 'থাইরয়েড ক্যান্সার',
        'Bladder Cancer' => 'মূত্রাশয়ের ক্যান্সার',
        'Pancreatic Cancer' => 'অগ্ন্যাশয়ের ক্যান্সার',
        'Ovarian Cancer' => 'ডিম্বাশয়ের ক্যান্সার',
        'Cervical Cancer' => 'জরায়ু মুখের ক্যান্সার',
        'Liver Cancer' => 'লিভার ক্যান্সার',
        'Stomach Cancer' => 'পাকস্থলীর ক্যান্সার',
        'Esophageal Cancer' => 'খাদ্যনালীর ক্যান্সার',
        'Psoriatic Arthritis' => 'সোরিয়াটিক আর্থ্রাইটিস',
        'Ankylosing Spondylitis' => 'অ্যানকাইলোজিং স্পন্ডিলাইটিস',
        "Sjogren's Syndrome" => 'সজোগ্রেন সিনড্রোম',
        "Raynaud's Disease" => 'রেনড রোগ',
        'Vitiligo' => 'শ্বেতী',
        'Alopecia' => 'অ্যালোপেসিয়া',
        'Rosacea' => 'রোজেসিয়া',
        'Acne' => 'ব্রণ',
        'Dermatitis' => 'ডার্মাটাইটিস',
        'Cellulitis' => 'সেলুলাইটিস',
        'Hypothyroidism' => 'হাইপোথাইরয়েডিজম',
        'Hyperthyroidism' => 'হাইপারথাইরয়েডিজম',
        "Addison's Disease" => 'অ্যাডিসন রোগ',
        "Cushing's Syndrome" => 'কুশিং সিনড্রোম',
        'Gestational Diabetes' => 'গর্ভকালীন ডায়াবেটিস',
    ],
];
